-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE TYPE auto_type AS ENUM(sedan, coupe, SUV, pickup);
CREATE TABLE IF NOT EXISTS public.steps
(
    step_id serial NOT NULL,
    step_name varchar(50),
    sampled boolean,
    x numeric,
    y numeric,
    upper_limit numeric,
    lower_limit numeric,
    nominal numeric,
    vin varchar(17) REFERENCES vehicles (vin), -- connect to vehicles table, see which vehicles the step is tied to.
    CONSTRAINT step_id PRIMARY KEY (step_id)
);

CREATE TABLE IF NOT EXISTS public.vehicles
(
    vin character varying(17) COLLATE pg_catalog."default",
    make character varying(50) COLLATE pg_catalog."default",
    model character varying(50) COLLATE pg_catalog."default",
    body_type auto_type,
    manufacture_date date,
    CONSTRAINT vin PRIMARY KEY (vin)
);
END;